# .github/workflows/test-runner.yml
name: Test Self-Hosted Runner

on: workflow_dispatch

jobs:
  test:
    runs-on: self-hosted
    steps:
      - run: |
          echo "Running on: $(hostname)"
          whoami
          docker ps